# Generated by Django 4.2.4 on 2023-09-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentingApp', '0003_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not_Available', 'Not_Available')], default='Available', max_length=30),
        ),
    ]
